{
 "title": "Storage Kpi (openstack)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ceph_rocksdb_submit_sync_latency_sum , cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Simin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ceph_health_status{cluster=\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{cluster=\"$cluster\"}) - sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_status{cluster=\"$cluster\"})",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_metadata{cluster=\"$cluster\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{cluster=\"$cluster\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{cluster=\"$cluster\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class) / sum(ceph_osd_stat_bytes{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class)",
     "legendFormat": "{{ device_class }}"
    }
   ]
  },
  {
   "title": "RBD Latency",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_rbd_write_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_write_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_rbd_read_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_read_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Total Pool IOPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Retransmission",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{instance=~\".*storage.*\"}[1m])) / sum(irate(node_netstat_Tcp_OutSegs{instance=~\".*storage.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(node_network_transmit_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(node_network_transmit_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Error"
    }
   ]
  },
  {
   "title": "Total Pool Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Mon Disk Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rocksdb_submit_sync_latency_sum{cluster=\"$cluster\"}[1m])/irate(ceph_rocksdb_submit_sync_latency_count{cluster=\"$cluster\"}[1m])"
    }
   ]
  },
  { "title": "shahriar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ceph_health_status{cluster=\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{cluster=\"$cluster\"}) - sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_status{cluster=\"$cluster\"})",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_metadata{cluster=\"$cluster\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{cluster=\"$cluster\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{cluster=\"$cluster\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class) / sum(ceph_osd_stat_bytes{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class)",
     "legendFormat": "{{ device_class }}"
    }
   ]
  },
  {
   "title": "RBD Latency",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_rbd_write_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_write_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_rbd_read_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_read_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Total Pool Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Retransmission",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{instance=~\".*storage.*\"}[1m])) / sum(irate(node_netstat_Tcp_OutSegs{instance=~\".*storage.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(node_network_transmit_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(node_network_transmit_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Error"
    }
   ]
  },
  {
   "title": "Total Pool IOPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Mon Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ceph_rocksdb_submit_sync_latency_sum{cluster=\"$cluster\"}[1m])/irate(ceph_rocksdb_submit_sync_latency_count{cluster=\"$cluster\"}[1m])"
    }
   ]
  },
  { "title": "Forough", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ceph_health_status{cluster=\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{cluster=\"$cluster\"}) - sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_status{cluster=\"$cluster\"})",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_metadata{cluster=\"$cluster\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{cluster=\"$cluster\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{cluster=\"$cluster\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class) / sum(ceph_osd_stat_bytes{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class)",
     "legendFormat": "{{ device_class }}"
    }
   ]
  },
  {
   "title": "RBD Latency",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_rbd_write_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_write_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_rbd_read_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_read_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Total Pool Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Retransmission",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{instance=~\".*storage.*\"}[1m])) / sum(irate(node_netstat_Tcp_OutSegs{instance=~\".*storage.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(node_network_transmit_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(node_network_transmit_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Error"
    }
   ]
  },
  {
   "title": "Total Pool IOPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Mon Disk Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rocksdb_submit_sync_latency_sum{cluster=\"$cluster\"}[1m])/irate(ceph_rocksdb_submit_sync_latency_count{cluster=\"$cluster\"}[1m])"
    }
   ]
  },
  { "title": "Bamdad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ceph_health_status{cluster=\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{cluster=\"$cluster\"}) - sum(ceph_mon_quorum_status{cluster=\"$cluster\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_status{cluster=\"$cluster\"})",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(ceph_mgr_metadata{cluster=\"$cluster\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{cluster=\"$cluster\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{cluster=\"$cluster\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class) / sum(ceph_osd_stat_bytes{cluster=\"$cluster\"} * on(ceph_daemon) group_left(device_class) ceph_osd_metadata{cluster=\"$cluster\"}) by (device_class)",
     "legendFormat": "{{ device_class }}"
    }
   ]
  },
  {
   "title": "RBD Latency",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_rbd_write_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_write_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_rbd_read_latency_sum{cluster=\"$cluster\"}[1m])) / sum(irate(ceph_rbd_read_latency_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Total Pool Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr_bytes{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Retransmission",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{instance=~\".*storage.*\"}[1m])) / sum(irate(node_netstat_Tcp_OutSegs{instance=~\".*storage.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(node_network_transmit_drop_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(node_network_transmit_errs_total{instance=~\".*storage.*\"}[1m]))",
     "legendFormat": "TX Error"
    }
   ]
  },
  {
   "title": "Total Pool IOPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_pool_wr{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Mon Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(ceph_rocksdb_submit_sync_latency_sum{cluster=\"$cluster\"}[1m])/irate(ceph_rocksdb_submit_sync_latency_count{cluster=\"$cluster\"}[1m])"
    }
   ]
  }
 ]
}