{
 "title": "libvirt network bandwith",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instaceid",
    "label": "instaceid",
    "query": {
     "query": "label_values(libvirt_domain_state_code{ job=\"prometheus-libvirt-exporter\"}, instanceId)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top Receivers",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, max(abs(delta(libvirt_domain_interface_stats_receive_bytes_total{}[$__range]))) by (instanceId,instanceName,projectName))",
     "legendFormat": "{{instanceName}} - {{instanceId}}"
    }
   ]
  },
  {
   "title": "Total Receives For  : $instaceid",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(delta(libvirt_domain_interface_stats_receive_bytes_total{instanceId=~\"$instaceid\"}[$__range])))",
     "legendFormat": "{{instanceName}} - {{instanceId}}"
    }
   ]
  },
  {
   "title": "Total Transmits  For  : $instaceid",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(delta(libvirt_domain_interface_stats_transmit_bytes_total{instanceId=~\"$instaceid\"}[$__range])))",
     "legendFormat": "{{instanceName}} - {{instanceId}}"
    }
   ]
  }
 ]
}