{
 "title": "Network Uptimes",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Beheshti",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max(probe_success{job=\"pingrange\",instance=\"85.208.253.254\"} or probe_success{job=\"pingrange\",instance=\"185.213.164.254\"} ) [$__range:5m] ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Apadana",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max(probe_success{job=\"pingrange\",instance=\"45.159.114.254\"} or probe_success{job=\"pingrange\",instance=\"185.116.161.254\"} or probe_success{job=\"pingrange\",instance=\"185.116.160.254\"} or probe_success{job=\"pingrange\",instance=\"185.116.162.254\"} or probe_success{job=\"pingrange\",instance=\"185.4.31.254\"} or probe_success{job=\"pingrange\",instance=\"185.116.163.254\"} ) [$__range:5m] ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SC1 Tehran (Imam)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"networkping\",instance=\"THR-SC1-sw-20061-Core.greenweb.local\"}  [$__range:5m] ) *  100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SC2 Tehran (LCT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"networkping\",instance=\"THR-SC2-05-sw-96154.greenweb.local\"}  [$__range:5m] ) *  100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pardis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max(probe_success{job=\"pingrange\",instance=\"185.4.29.254\"} or probe_success{job=\"pingrange\",instance=\"185.4.30.254\"} or probe_success{job=\"pingrange\",instance=\"185.4.28.1\"} ) [$__range:5m] ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tebyan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"pingrange\",instance=~\"85.208.255.254\"}  [$__range:5m] ) *  100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tabriz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max(probe_success{job=\"pingrange\",instance=\"185.213.167.254\"} or probe_success{job=\"pingrange\",instance=\"5.182.46.254\"} or probe_success{job=\"pingrange\",instance=\"5.182.44.254\"} or probe_success{job=\"pingrange\",instance=\"45.159.113.254\"} or probe_success{job=\"pingrange\",instance=\"193.141.126.254\"} or probe_success{job=\"pingrange\",instance=\"193.141.65.254\"} or probe_success{job=\"pingrange\",instance=\"185.255.90.254\"} or probe_success{job=\"pingrange\",instance=\"185.255.89.254\"} or probe_success{job=\"pingrange\",instance=\"85.208.254.254\"} or probe_success{job=\"pingrange\",instance=\"45.159.115.254\"} or probe_success{job=\"pingrange\",instance=\"185.255.88.254\"} or probe_success{job=\"pingrange\",instance=\"193.141.127.254\"}  or probe_success{job=\"pingrange\",instance=\"185.255.91.254\"}  ) [$__range:5m] ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Switch Ping Uptime",
   "type": "stat",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"networkping\",instance=~\".*sw.*\"}  [$__range] ) *  100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}