{
 "title": "Openstack Resource Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Cinder Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_cinder_up ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keystone Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_identity_up ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cinder Capacity Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_total_gb",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cinder Capacity Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_free_gb",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Free Public IP Availabilities ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_network_ip_availabilities_total{subnet_name=~\"public.*\"} - openstack_neutron_network_ip_availabilities_used{subnet_name=~\"public.*\"} ",
     "legendFormat": "{{cidr}}"
    }
   ]
  },
  {
   "title": "Glance Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_glance_up  ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heat Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_heat_up ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Glance Image Size (Snapshot and Base Images)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_glance_image_bytes)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Local Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(openstack_nova_local_storage_available_bytes) - sum(openstack_nova_free_disk_bytes) ) / sum(openstack_nova_local_storage_available_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes) / sum(openstack_nova_memory_available_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ( Ratio 3 )",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used) / (sum(openstack_nova_vcpus_available)*3) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public IP Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_network_ip_availabilities_used{subnet_name=~\"public.*\"} ) / (sum(openstack_neutron_network_ip_availabilities_total{subnet_name=~\"public.*\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Neutron Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_up ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Placement Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_placement_up ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nova Total VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_nova_total_vms ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nova Flavors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_nova_flavors ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_networks ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Neutron Routers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_neutron_routers ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Security Groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_security_groups ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Floating IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_floating_ips ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Zones ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_availability_zones ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity Projects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_identity_projects ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Glance Images",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_glance_images", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cinder Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_cinder_volumes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nova Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_nova_up ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compute Total Disk Space",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "openstack_nova_local_storage_available_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Free  Disk Space",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "openstack_nova_free_disk_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compute Free  Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "openstack_nova_memory_available_bytes - openstack_nova_memory_used_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Total vCPUs ( Ratio 3 )",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openstack_nova_vcpus_available * 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Free  vCPUs ( Ratio 3 )",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openstack_nova_vcpus_available * 3 - openstack_nova_vcpus_used ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Running VMs",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "openstack_nova_running_vms", "legendFormat": "__auto" }
   ]
  }
 ]
}